### ISSUE TITLE
New recordings are badly truncated

### ISSUE THREAD

**Issue by carlogico** [Jakobovski/free-spoken-digit-dataset#15]
Hi. I was listening to the new samples from Jason, a lot of them are badly truncated at the beginning.

**Comment by speechwrecko** [comment]
Thanks for QA'ing.  Any suggestion on if they can be fixed.   I still have
my source recording.   I used the existing script .. I can muck with some
of the timings on how the files are split if that would help

**Comment by carlogico** [comment]
I haven't played around with trimmer.py, but it looks like playing around with min_silence_duration and noise_threshold should give you the correct result.

**Comment by Jakobovski** [comment]
Thanks carlogico.  Yes that is correct you need to play around with those settings. Additionally, it may be necessary to do some manual trimming on my recordings.

**Comment by Jakobovski** [comment]
@speechwrecko . Is there an update on when you will have the recordings fixed? If it is going to be a while then I will remove them from the dataset..

**Comment by Jakobovski** [comment]
@speechwrecko . if you send me the original files i will trim them for you

**Comment by carlogico** [comment]
If the new files are not trimmed, they probably should be removed from the repo or a strong disclaimer should be written.

**Comment by Jakobovski** [comment]
Agree. I will remove them tonight because @speechwrecko  is not responding

**Comment by Jakobovski** [comment]
Jason's recordings have been removed
