### ISSUE TITLE
problem of 8bit&16bit

### ISSUE THREAD

**Issue by tangsipeng** [Jakobovski/free-spoken-digit-dataset#16]
some files are 8bit like 1_nicolas_36.wav  
some files are 16bit like  9_theo_22.wav
it hard to deal with two diffient  Sampling number 
how can i unified？

**Comment by slegroux** [comment]
you can use sox (apt-get install sox if not installed on your system) to convert to proper encoding
```sox -b 16 -e signed-int old_nicolas.wav new_nicolas.wav```

**Comment by Jakobovski** [comment]
Would you like to update the repository so that all files are 16bit?

**Comment by slegroux** [comment]
Hi,
Sure, I can do that. Will try to send a PR today.
S.

**Comment by Jakobovski** [comment]
fixed
