### ISSUE TITLE
.wav encoding for speaker Nicolas not consistent with other speakers

### ISSUE THREAD

**Issue by slegroux** [Jakobovski/free-spoken-digit-dataset#17]
FYI file encoding for speaker nicolas are 8bit unsigned integer whereas all other speakers are 16bit Signed int
```sox -b 16 -e signed-int old_nicolas.wav new_nicolas.wav```
does the trick

**Comment by cag51** [comment]
Nicolas also seems to be stereo (2 channels) instead of one. This seems to solve both problems:
`ffmpeg -i data/2_nicolas_4.wav -af 'pan=mono|c0=c1' nicolas_mono/2_nicolas_4.wav`

**Comment by Jakobovski** [comment]
Fixed
