### ISSUE TITLE
adding more numbers 

### ISSUE THREAD

**Issue by Nourahussein** [Jakobovski/free-spoken-digit-dataset#21]
I think it will be better if you add numbers like  20,30,40,50,60,70,80,90,100 and from 11:20
so we can have all the numbers combinations, so for example, if we use this dataset in application to recognize numbers like 3.45, 578, or 54 this dataset after improving  will help a lot

**Comment by Jakobovski** [comment]
I would be open to adding these. Would you like to contribute?

**Comment by Nourahussein** [comment]
of course, let me know how can I contribute, by my voice? or by improving the code?

**Comment by Jakobovski** [comment]
Yes I mean you can add recordings of your voice for all the numbers you want
