### ISSUE TITLE
About reference

### ISSUE THREAD

**Issue by Redemfre** [Jakobovski/free-spoken-digit-dataset#25]
Thank you for your work，Please tell me if I want to use this data set in my paper，what citation format should I use？

**Comment by Jakobovski** [comment]
The project contains a DOI which can be used for citations
https://zenodo.org/record/1342401

As for the format it depends on where you are publishing

**Comment by Jakobovski** [comment]
If you look at the link above you will see an input element where one can select the desired style and it will produce the appropriate citation.

**Comment by Redemfre** [comment]
I'm sorry I still can't find a valid citation format
When I open the link, there are three headings:Preview, Files, Citations
However, I didn't find a format to use for references
I'm confused, could you please give me a right reference to thanks for your work in my paper?
or the artical 'Regularization of Hidden Markov Models Embedded into Reproducing Kernel Hilbert Space'is  your masterpiece and I can quote it as an illustration and thanks?
