### ISSUE TITLE
How can we record 8KHz Mono WAV format file for Digit Classification?

### ISSUE THREAD

**Issue by azeemabbas** [Jakobovski/free-spoken-digit-dataset#28]
I used this code for training a model to classify free-spoken-digit-dataset (https://github.com/mikesmales/Udacity-ML-Capstone). The accuracy of the trained model is 96%.

But the prediction using the saved model fails when I test it for my recorded voice. I recorded some digits using windows 10 voice recorder and converted files to 8KHz Mono WAV format.

Any help you can provide? The model predicts accurately on the recordings provided within the dataset.

My Recorded Digit 3:

Original sample rate: 22050
Librosa sample rate: 22050
Original audio file minmax range: 20 to 239
Librosa audio file minmax range: -0.84375 to 0.8671875
(40, 18)

Dataset : Jackson 3:

Original sample rate: 8000
Librosa sample rate: 22050
Original audio file minmax range: -10989 to 9277
Librosa audio file minmax range: -0.35349792 to 0.28417692
(40, 21)

**Comment by Jakobovski** [comment]
It might just be an issue of not enough data to train the model. The training set is very small.

Try adding your voice to the training set.
