### ISSUE TITLE
The dataset contains 1501 recordings

### ISSUE THREAD

**Issue by cesarsouza** [Jakobovski/free-spoken-digit-dataset#8]
Currently, the dataset contains 1501 recordings instead of the 1500 described in the readme. If you [check the list of files currently at the recordings directory](https://api.github.com/repositories/61622039/git/trees/ee8c3d6b556fd70607ccaae089abad378d4d257c), you will see that it contains a file named "6_jackson_**50**.wav". However the maximum possible number label for the index should have been 49 instead of 50.

**Comment by Jakobovski** [comment]
Feel free to delete the file and create a pull request,

**Comment by ManivannanMurugavel** [comment]
Use this code to download the .wav files
```
import os

speakers = ['jackson','nicolas','theo','yweweler']

src_path = 'https://raw.githubusercontent.com/Jakobovski/free-spoken-digit-dataset/master/recordings'


for number in range(10):
	for speaker in speakers:
		for idx in range(50):
			filename = '{}_{}_{}.wav'.format(number,speaker,idx)
			url = os.path.join(src_path,filename)
			os.system('wget {}'.format(url))
```

**Comment by Jakobovski** [comment]
@ManivannanMurugavel  Why did you write this comment?

**Comment by ManivannanMurugavel** [comment]
This is a help to download the all .wav file without git clone.
